# Generated by Django 4.2.16 on 2024-11-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
